Добавить контроллеры Предметов и Пользователей, реализовать работу да…
KirillSenchenkov/java-shareit pull request #2
Opened 2023-08-20 12:09 UTC by KirillSenchenkov

…нных контроллеров

2023-08-20 12:13 UTC, KirillSenchenkov commented
Прошу прощения за кривой коммит, я честно говоря не знаю как так вышло. 
![image](https://github.com/KirillSenchenkov/java-shareit/assets/120310076/bdb52c47-60bc-4598-8e07-f5d1da0f9fdb)
сделал как обычно

2023-08-20 20:23 UTC, sergeymamonov commented
> Прошу прощения за кривой коммит, я честно говоря не знаю как так вышло. ![image](https://user-images.githubusercontent.com/120310076/261851062-bdb52c47-60bc-4598-8e07-f5d1da0f9fdb.png) сделал как обычно

Не очень понял в чем сложность? В названии пулл реквеста? В гитхабе в самом ПРе вы разве не можете его поменять? Или еще в чем-то сложность?

2023-08-20 20:35 UTC, sergeymamonov requested changes

2023-08-20 20:35 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/item/ItemMapper.java
> +    public List<ItemDto> itemToItemDtoList(List<Item> items) {
Этот метод где-то используется?

2023-08-20 20:35 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/service/ErrorHandler.java
> +}
Лучше еще сделать обработку RuntimeException.
EmailExistException приведет к 409 ошибке.

2023-08-22 21:05 UTC, sergeymamonov commented
Тред (замечание) резолвит тот, кто его открыл. Вы можете ответить, что сделали, или поставить какую-то реакцию, но не закрывать. Потому что когда проверяешь замечание, его приходится сначала открыть, это неудобно.

2023-08-22 21:07 UTC, sergeymamonov approved these changes

2023-08-22 21:07 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/service/ErrorHandler.java
> +}
Обработчик RuntimeException должен возвращать 500 код.
А на EmailExistException должен быть свой обработчик, который будет возвращать 409 код.

2023-09-03 18:11 UTC, merged