Реализовать сервис бронирования
KirillSenchenkov/java-shareit pull request #4
Opened 2023-09-16 16:30 UTC by KirillSenchenkov

Реализовать сервис бронирования, реализовать репозитории, подключить базу данных

2023-09-18 12:29 UTC, sergeymamonov requested changes

2023-09-18 12:29 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +                || (!Objects.equals(bookingRepository.findById(bookingId).get().getItem().getOwnerId(), userId))) {
get у Optional вызывается только после проверки (ifPresent). Посмотрите везде, где используете get у Optional.

2023-09-18 12:29 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +        if (booking.getStatus().equals(BookingStatus.APPROVED)) {
Лучше наоборот. Метод equals необходимо вызывать у константы или у значения, которое гарантированно не равно null. Потому что если значение, у которого вызывается метод equals будет равно null, то получим NPE. Проверьте во всем коде, как вызывается метод equals.

2023-09-18 12:29 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +            itemDto.setNextBooking(getFutureBookingFotItem(itemDtoId));
В этих двух строках запросы к БД в цикле. Не очень хорошо делать запросы к БД в цикле. Это большая нагрузка на БД. Затратно по времени из-за передачи по сети.

2023-09-18 12:29 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +    public Boolean findUserById(Long userId) {
Сначала в классе размещают публичные методы, а потом приватные.

2023-09-18 17:08 UTC, KirillSenchenkov commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +            itemDto.setNextBooking(getFutureBookingFotItem(itemDtoId));
Не могу понять как мне реализовать данную правку, делаю запрос на основании некого листа с айдишками предметов и убираю вообще методы гетласт гетфьючер ?

2023-09-19 10:33 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +            itemDto.setNextBooking(getFutureBookingFotItem(itemDtoId));
Из БД можно получать набор строк где какое-то значение из этих строк из списка. То есть в данном случае можно получить все бронирования для всех вещей. А потом для каждой вещи из этих бронирований найти нужные бронирования.

2023-09-20 10:29 UTC, sergeymamonov approved these changes

2023-09-20 15:01 UTC, merged